const CONFIG={endpoint:'/api/events',refreshSeconds:120,requestTimeoutMs:15000};
const CATEGORIES={conflict:{label:'Conflict',color:'#ff5d6c'},earthquake:{label:'Earthquake',color:'#ffd24d'},wildfire:{label:'Wildfire',color:'#ff843d'},storm:{label:'Storm',color:'#45a3ff'},volcano:{label:'Volcano',color:'#d586ff'},flood:{label:'Flood',color:'#32c8df'},other:{label:'Other hazard',color:'#68d6b7'}};
const SEVERITIES={critical:{label:'Critical',color:'#ff355d',score:4},high:{label:'High',color:'#ff8a3d',score:3},medium:{label:'Medium',color:'#f6c453',score:2},low:{label:'Low',color:'#45a3ff',score:1}};
const map=L.map('map',{zoomControl:false,minZoom:2,worldCopyJump:true,preferCanvas:true}).setView([22,10],2.35);L.control.zoom({position:'bottomright'}).addTo(map);
const basemaps={
 satellite:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and contributors'}),
 labels:L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Labels © Esri',pane:'overlayPane'}),
 dark:L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:'© OpenStreetMap © CARTO'}),
 street:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'})
};
basemaps.satellite.addTo(map);basemaps.labels.addTo(map);let activeBase='satellite';const markerLayer=L.layerGroup().addTo(map);
let state={events:[],categories:new Set(Object.keys(CATEGORIES)),severities:new Set(Object.keys(SEVERITIES)),query:'',hours:168,sort:'severity',lastLoaded:null};
const ids=['layerFilters','severityFilters','eventList','visibleCount','highCount','countryCount','updatedAt','search','clearFilters','timeWindow','sortOrder','fitWorld','fitEvents','themeToggle','eventDialog','dialogContent','closeDialog','mapLegend','systemStatus','feedAge','baseMap','refreshNow'];const els=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function relativeTime(ts){const d=Math.max(0,Date.now()-Number(ts)),m=Math.floor(d/60000),h=Math.floor(m/60);if(m<1)return'just now';if(h<1)return`${m}m ago`;if(h<24)return`${h}h ago`;return`${Math.floor(h/24)}d ago`}
function exactTime(ts){return new Date(ts).toLocaleString([],{dateStyle:'medium',timeStyle:'long'})}
function safeCategory(c){return CATEGORIES[c]?c:'other'}function safeSeverity(s){return SEVERITIES[s]?s:'low'}
function normalizeEvent(e){return{...e,category:safeCategory(e.category),severity:safeSeverity(e.severity),occurredAt:Number(e.occurredAt||Date.now()),lat:Number(e.lat),lon:Number(e.lon),confidence:Number(e.confidence||80),details:e.details||{}}}
function quakeSeverity(m){return m>=7?'critical':m>=6?'high':m>=4.5?'medium':'low'}
function normalizeUSGS(f){const p=f.properties||{},coords=f.geometry?.coordinates||[0,0,0],mag=Number(p.mag||0),depth=Number(coords[2]||0);return normalizeEvent({id:`usgs-${f.id}`,category:'earthquake',severity:quakeSeverity(mag),title:p.title||`Magnitude ${mag.toFixed(1)} earthquake`,summary:`Magnitude ${mag.toFixed(1)} earthquake at approximately ${depth.toFixed(1)} km depth. ${p.status==='reviewed'?'Reviewed by USGS.':'Preliminary automated solution; details may change.'}`,lat:coords[1],lon:coords[0],country:(p.place||'Unknown').split(',').pop().trim(),place:p.place||'Unknown location',occurredAt:p.time,updatedAt:p.updated,source:'USGS Earthquake Hazards Program',sourceUrl:p.url,confidence:p.status==='reviewed'?98:90,details:{Magnitude:mag.toFixed(1),Depth:`${depth.toFixed(1)} km`,Status:p.status||'unknown',Tsunami:p.tsunami?'Possible/flagged':'No flag',Felt:p.felt??'Not reported',Significance:p.sig??'—',Coordinates:`${coords[1].toFixed(4)}, ${coords[0].toFixed(4)}`}})}
async function directFallback(){const r=await fetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson',{cache:'no-store'});if(!r.ok)throw new Error(`USGS ${r.status}`);const d=await r.json();return{events:d.features.map(normalizeUSGS),generatedAt:Date.now(),sources:['USGS direct fallback'],mode:'fallback'}}
async function loadEvents(manual=false){els.systemStatus.innerHTML='<i></i> Updating';els.refreshNow.disabled=true;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),CONFIG.requestTimeoutMs);try{let result;try{const r=await fetch(`${CONFIG.endpoint}?hours=${state.hours}&t=${Date.now()}`,{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error(`API ${r.status}`);result=await r.json()}catch(apiError){console.warn('Netlify function unavailable; using direct USGS fallback.',apiError);result=await directFallback()}state.events=(result.events||[]).map(normalizeEvent).filter(e=>Number.isFinite(e.lat)&&Number.isFinite(e.lon));state.lastLoaded=Number(result.generatedAt||Date.now());els.systemStatus.innerHTML=`<i></i> ${result.mode==='fallback'?'Live fallback':'Live multi-source'}`;render()}catch(err){console.error(err);els.systemStatus.textContent='Feed unavailable';if(!state.events.length)els.eventList.innerHTML='<div class="empty">Could not load a live feed. Check Netlify Functions logs and deployment settings.</div>'}finally{clearTimeout(timeout);els.refreshNow.disabled=false;if(manual)els.refreshNow.textContent='Refreshed';setTimeout(()=>els.refreshNow.textContent='Refresh',1200)}}
function filteredEvents(){const cutoff=Date.now()-state.hours*3600000,q=state.query.trim().toLowerCase();let out=state.events.filter(e=>state.categories.has(e.category)&&state.severities.has(e.severity)&&e.occurredAt>=cutoff);if(q)out=out.filter(e=>`${e.title} ${e.summary} ${e.country} ${e.place} ${e.source} ${JSON.stringify(e.details)}`.toLowerCase().includes(q));return out.sort((a,b)=>state.sort==='newest'?b.occurredAt-a.occurredAt:(SEVERITIES[b.severity].score-SEVERITIES[a.severity].score)||(b.occurredAt-a.occurredAt))}
function renderFilters(){els.layerFilters.innerHTML=Object.entries(CATEGORIES).map(([k,c])=>`<button class="filter-item ${state.categories.has(k)?'active':''}" style="--category:${c.color}" data-category="${k}"><span><i class="dot"></i>${c.label}</span><b>${state.events.filter(e=>e.category===k).length}</b></button>`).join('');els.severityFilters.innerHTML=Object.entries(SEVERITIES).map(([k,s])=>`<button class="severity-btn ${state.severities.has(k)?'active':''}" style="--sev:${s.color}" data-severity="${k}">${s.label}</button>`).join('');els.mapLegend.innerHTML=Object.values(CATEGORIES).map(c=>`<div class="legend-row"><i class="dot" style="--category:${c.color}"></i>${c.label}</div>`).join('')}
function markerIcon(e){return L.divIcon({className:'',html:`<div class="event-marker" style="--marker:${CATEGORIES[e.category].color}"></div>`,iconSize:[15,15],iconAnchor:[7,7]})}
function renderMap(events){markerLayer.clearLayers();events.forEach(e=>{const m=L.marker([e.lat,e.lon],{icon:markerIcon(e)}).addTo(markerLayer);m.bindTooltip(`<strong>${esc(e.title)}</strong><br>${esc(e.place)} · ${relativeTime(e.occurredAt)}`,{direction:'top'});m.on('click',()=>openEvent(e))})}
function keyFacts(e){return Object.entries(e.details||{}).slice(0,3).map(([k,v])=>`<span class="fact-chip">${esc(k)}: ${esc(v)}</span>`).join('')}
function renderList(events){els.eventList.innerHTML=events.length?events.map(e=>`<article class="event-card" data-id="${esc(e.id)}"><div class="event-meta"><span class="category-pill" style="--cat:${CATEGORIES[e.category].color}">${CATEGORIES[e.category].label}</span><span>${esc(e.country)}</span><span class="severity-tag" style="--sev:${SEVERITIES[e.severity].color}">${SEVERITIES[e.severity].label}</span></div><h2>${esc(e.title)}</h2><p>${esc(e.summary)}</p><div class="event-facts">${keyFacts(e)}</div><div class="event-foot"><span>${relativeTime(e.occurredAt)} · ${esc(e.source)}</span><span class="confidence">${e.confidence}% confidence</span></div></article>`).join(''):'<div class="empty">No events match the selected filters and time range.</div>'}
function renderStats(events){els.visibleCount.textContent=events.length;els.highCount.textContent=events.filter(e=>['critical','high'].includes(e.severity)).length;els.countryCount.textContent=new Set(events.map(e=>e.country).filter(Boolean)).size;els.updatedAt.textContent=state.lastLoaded?new Date(state.lastLoaded).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—';els.feedAge.textContent=state.lastLoaded?`Feed ${relativeTime(state.lastLoaded)}`:'—'}
function render(){renderFilters();const events=filteredEvents();renderMap(events);renderList(events);renderStats(events)}
function openEvent(e){const rows={...e.details,'Exact reported time':exactTime(e.occurredAt),'UTC time':new Date(e.occurredAt).toISOString(),'Latitude':e.lat.toFixed(5),'Longitude':e.lon.toFixed(5),'Source confidence':`${e.confidence}%`};els.dialogContent.innerHTML=`<div class="dialog-kicker">${CATEGORIES[e.category].label} · ${SEVERITIES[e.severity].label}</div><h2 class="dialog-title">${esc(e.title)}</h2><p class="dialog-summary">${esc(e.summary)}</p><div class="dialog-grid"><div><span>Location</span><strong>${esc(e.place)}</strong></div><div><span>Reported</span><strong>${esc(exactTime(e.occurredAt))}</strong></div><div><span>Provider</span><strong>${esc(e.source)}</strong></div></div><table class="details-table"><tbody>${Object.entries(rows).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</tbody></table><a class="source-link" href="${esc(e.sourceUrl||'#')}" target="_blank" rel="noopener noreferrer">Open original source ↗</a>`;els.eventDialog.showModal();map.flyTo([e.lat,e.lon],Math.max(map.getZoom(),5))}
function switchBase(name){Object.values(basemaps).forEach(l=>map.hasLayer(l)&&map.removeLayer(l));activeBase=name;if(name==='satellite'){basemaps.satellite.addTo(map);basemaps.labels.addTo(map)}else basemaps[name].addTo(map);markerLayer.bringToFront()}
document.addEventListener('click',ev=>{const cat=ev.target.closest('[data-category]');if(cat){const k=cat.dataset.category;state.categories.has(k)?state.categories.delete(k):state.categories.add(k);render()}const sev=ev.target.closest('[data-severity]');if(sev){const k=sev.dataset.severity;state.severities.has(k)?state.severities.delete(k):state.severities.add(k);render()}const card=ev.target.closest('[data-id]');if(card){const e=state.events.find(x=>x.id===card.dataset.id);if(e)openEvent(e)}});
els.search.addEventListener('input',e=>{state.query=e.target.value;render()});els.timeWindow.addEventListener('change',e=>{state.hours=Number(e.target.value);loadEvents()});els.sortOrder.addEventListener('change',e=>{state.sort=e.target.value;render()});els.clearFilters.addEventListener('click',()=>{state.categories=new Set(Object.keys(CATEGORIES));state.severities=new Set(Object.keys(SEVERITIES));state.query='';els.search.value='';render()});els.fitWorld.addEventListener('click',()=>map.setView([22,10],2.35));els.fitEvents.addEventListener('click',()=>{const e=filteredEvents();if(e.length)map.fitBounds(e.map(x=>[x.lat,x.lon]),{padding:[40,40],maxZoom:7})});els.baseMap.addEventListener('change',e=>switchBase(e.target.value));els.refreshNow.addEventListener('click',()=>loadEvents(true));els.themeToggle.addEventListener('click',()=>document.documentElement.classList.toggle('light'));els.closeDialog.addEventListener('click',()=>els.eventDialog.close());els.eventDialog.addEventListener('click',e=>{if(e.target===els.eventDialog)els.eventDialog.close()});
loadEvents();setInterval(loadEvents,CONFIG.refreshSeconds*1000);setInterval(()=>renderStats(filteredEvents()),30000);
